### ISSUE TITLE
docker: cannot get docker to run with sudo

### ISSUE THREAD

**Issue by mbana** [CircleCI-Public/circleci-dockerfiles#6]
Hello, I am trying to get docker in docker (dind) running but I cannot seem to run `docker` as it requires me to prefix all the commands with sudo. I have a few questions:

1. How do I get it to run without prefixing all the `docker` and `docker-compose` commands with `sudo`.
2. Why not just install `docker` from the package manager instead of doing it manually?
3. The command listed here isn't available in the image: https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/elixir/images/1.6.5/Dockerfile#L45. As in running `/usr/local/bin/dockerd` just before `docker-compose build` doesn' help.
4. Can you please show a complete working example of `docker` in `docker` with the `circleci/elixir:1.6-node`, please.

Thanks

**Config**

```yaml
version: 2

jobs:
  test_job:
    docker:
      - image: circleci/elixir:1.6-node
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Building
          command: |
            # sudo groupadd docker
            # sudo usermod -a -G docker $(whoami)
            docker-compose build

workflows:
  version: 2
  test-deploy:
    jobs:
      - test_job
      - post_test_job
```
